version: "3.9"

services:
  neo4j:
    image: neo4j:5.2
    ports:
      - target: 7474
        published: 7474
      - target: 7687 # web ui
        published: 7687
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs
    environment:
      NEO4J_AUTH: neo4j/password
    # volumes:
    #   - neo4j-core-conf:/conf
    #   - neo4j-core-data:/data
    #   - neo4j-core-logs:/logs
    #   - neo4j-core-import:/var/lib/neo4j/import
    #   - neo4j-core-metrics:/metrics
    #   - neo4j-core-plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
