/* this code was generated by automated tool, 
   should not edit by hand */

export interface Recommender {
  GetSimilarVideos(request: GetSimilarVideosRequest): Promise<GetSimilarVideosReply>;
}

export interface GetSimilarVideosRequest {
  videoId?: string;
  limit?: number;
}

export interface GetSimilarVideosReply {
  similarities?: Similarity[];
}

export interface Similarity {
  videoId?: string;
  score?: number;
}
